"""
Budget analysis model.

Stores the budget evaluation generated by the Budget Agent.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class CostBreakdown(BaseModel):
    """Estimated cost distribution."""

    accommodation: float = Field(..., ge=0)
    transport: float = Field(..., ge=0)
    food: float = Field(..., ge=0)
    activities: float = Field(..., ge=0)
    miscellaneous: float = Field(..., ge=0)


class BudgetAnalysis(BaseModel):
    """Budget evaluation for the planned trip."""

    total_estimated: float = Field(
        ...,
        ge=0,
        description="Estimated total trip cost",
    )

    remaining_budget: float = Field(
        ...,
        description="Remaining budget after estimated expenses",
    )

    feasible: bool = Field(
        ...,
        description="Whether the trip fits within the user's budget",
    )

    breakdown: CostBreakdown = Field(
        ...,
        description="Estimated cost breakdown",
    )

    recommendations: List[str] = Field(
        default_factory=list,
        description="Practical suggestions if budget is exceeded",
    )

    notes: str | None = Field(
        default=None,
        description="Suggestions for reducing costs or improving the budget",
    )