"""
Climate assessment model.

Stores the weather analysis generated by the Climate Agent.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class ClimateAssessment(BaseModel):
    """Weather analysis for the selected destination and travel period."""

    weather_risk: Literal["low", "medium", "high"] = Field(
        ...,
        description="Overall weather risk level",
    )

    avg_temp_c: float = Field(
        ...,
        description="Average expected temperature in Celsius",
    )

    precipitation_mm: float = Field(
        ...,
        ge=0,
        description="Expected precipitation in millimeters",
    )

    weather_summary: str | None = Field(
        default=None,
        description="Short summary of the expected weather",
    )