"""
Route plan model.

This model stores the optimized route generated by the Transport Agent.
It is shared through TripState and later used by the Budget Agent and
Composer Agent.
"""

from __future__ import annotations

from typing import List, Literal

from pydantic import BaseModel, Field


class CityRoute(BaseModel):
    """Optimized route within a single city."""

    city: str = Field(
        ...,
        description="City name",
    )
    attraction_order: List[str] = Field(
        default_factory=list,
        description="Optimized order of attraction names within this city",
    )
    distance_km: float = Field(
        default=0.0,
        ge=0,
        description="Travel distance within this city in km",
    )
    duration_minutes: int = Field(
        default=0,
        ge=0,
        description="Travel duration within this city in minutes",
    )


class RoutePlan(BaseModel):
    """Optimized travel route between recommended attractions."""

    total_distance_km: float = Field(
        ...,
        ge=0,
        description="Total travel distance in kilometers",
    )

    total_duration_minutes: int = Field(
        ...,
        ge=0,
        description="Estimated total travel time in minutes",
    )

    recommended_transport: Literal[
        "walking",
        "car",
        "bike",
        "suv",
        "minivan",
        "public_transport",
    ] = Field(
        ...,
        description="Recommended mode of transport",
    )

    optimized_order: List[str] = Field(
        default_factory=list,
        description="Optimized order of attractions to visit",
    )

    city_order: List[str] = Field(
        default_factory=list,
        description="Optimized order of cities for multi-location trips",
    )

    city_routes: List[CityRoute] = Field(
        default_factory=list,
        description="Per-city route breakdown for multi-location trips",
    )

    notes: str | None = Field(
        default=None,
        description="Additional travel recommendations or route notes",
    )
