# models/trip_state.py
"""
TripState – shared state used by all agents.

The model contains:
- User constraints (owned by Planner)
- Agent outputs (owned by their respective agents)
- Decision log (append‑only for all agents)

All fields are typed and validated using Pydantic v2.
"""

from __future__ import annotations

from typing import List, Literal, Optional
from datetime import date
from pydantic import BaseModel, Field

# Nested models from other files
from models.climate_assessment import ClimateAssessment
from models.experience import Experience
from models.route_plan import RoutePlan
from models.budget_analysis import BudgetAnalysis


class TripState(BaseModel):
    """Central state shared across the multi‑agent planning pipeline."""

    # ------------------------ User Constraints ------------------------
    destination: Optional[str] = Field(
        default=None,
        description="User‑specified travel destination",
    )
    start_date: Optional[date] = Field(
        default=None,
        description="Trip start date",
    )

    end_date: Optional[date] = Field(
        default=None,
        description="Trip end date",
    )
    duration_days: Optional[int] = Field(
        default=None,
        ge=1,
        description="Length of the trip in days",
    )

    travel_month: Optional[int] = Field(
        default=None,
        ge=1,
        le=12,
        description="Travel month if exact dates are unavailable",
    )

    travel_year: Optional[int] = Field(
        default=None,
        ge=2000,
        description="Travel year if exact dates are unavailable",
    )

    latitude: Optional[float] = Field(
        default=None,
        description="Latitude of the destination",
    )

    longitude: Optional[float] = Field(
        default=None,
        description="Longitude of the destination",
    )

    budget: Optional[float] = Field(
        default=None,
        ge=0,
        description="Total budget allocated by the user",
    )
    traveler_type: Optional[Literal["solo", "couple", "family", "group"]] = Field(
        default=None,
        description="Category of travelers",
    )
    number_of_travelers: Optional[int] = Field(
        default=None,
        ge=1,
        description="Total number of travelers",
    )
    accommodation_preference: Optional[
        Literal["hotel", "hostel", "resort", "homestay", "airbnb", "camping"]
    ] = Field(
        default=None,
        description="Preferred type of accommodation",
    )
    children_count: Optional[int] = Field(
        default=None,
        ge=0,
        description="Number of children in the travel group",
    )
    senior_citizens_count: Optional[int] = Field(
        default=None,
        ge=0,
        description="Number of senior citizens in the travel group",
    )
    travel_style: Optional[Literal["budget", "mid-range", "luxury"]] = Field(
        default=None,
        description="Preferred travel style",
    )
    interests: List[str] = Field(
        default_factory=list,
        description="User interests",
    )

    trip_scope: Optional[Literal["single_location", "multi_location"]] = Field(
        default="single_location",
        description="Whether the trip covers one destination or multiple destinations within a region.",
    )

    # ------------------------ Agent Outputs -------------------------
    climate_assessment: Optional[ClimateAssessment] = Field(
        default=None,
        description="Weather analysis produced by the Climate Agent",
    )
    recommended_experiences: Optional[Experience] = Field(
        default=None,
        description="Attractions and activities from the Destination Agent",
    )
    optimized_route: Optional[RoutePlan] = Field(
        default=None,
        description="Optimized travel route from the Transport Agent",
    )
    budget_analysis: Optional[BudgetAnalysis] = Field(
        default=None,
        description="Budget evaluation from the Budget Agent",
    )
    itinerary: Optional[str] = Field(
        default=None,
        description="Final day‑wise itinerary generated by the Composer Agent",
    )

    # ------------------------ Workflow -------------------------
    workflow: List[str] = Field(
    default_factory=list,
    description="Execution workflow decided by PlannerAgent.",
)

    replan_attempts: int = Field(
    default=0,
    ge=0,
    description="Number of automatic replanning attempts.",
)

    # ------------------------ Misc -------------------------
    decision_log: List[str] = Field(
        default_factory=list,
        description="Chronological log of decisions made by any agent",
    )
